### ISSUE TITLE
建议增加“保准”（assert）和“整岔劈了”（Exception）

### ISSUE THREAD

**Issue by Lafite-Yu** [zhanyong-wan/dongbei#10]
保准 判定条件
若判定了了，没毛病，则接着跑，否则抛出整岔劈了

咋 整岔劈了
抛出毛病的同时，打印咋整岔劈了的解释，咋应是个字符串

**Comment by Co2333** [comment]
assert??? asset???

**Comment by Lafite-Yu** [comment]
> assert??? asset???

整岔劈了

**Comment by ESWZY** [comment]
throw是整
Exception是叉劈了
整不是关键字吧哈哈哈哈哈
我现在已经不认识整字了 🤣 🤣 🤣

**Comment by megabitsenmzq** [comment]
还可以加入

急了拐弯（指思维复杂，绕，或单纯指路线转弯多）
秃了反涨（指衣服穿着等不整齐，这里凸一块，那里凸一块的）
捂了嚎疯（指心情急躁的状态）
吭哧瘪肚（指常常受气，或做事被动）
毛了三光（指做事不假思索，想什么干什么）

等东北话常用/专有四字词语

以及

简直（表示直走的那个意思）
呐（nē）（指牛逼）

等意思比较特殊的词汇

感觉放进关键字还是错误提示都挺牛逼的。（就是有些词真的不知道那个发音该对哪个字）（意思都是我自己写的，不是找字典查的，如果有叉劈的还请各位指教）

**Comment by intentc** [comment]
这个逗，西斯

**Comment by idealclover** [comment]
试着整整（try）
整岔劈了（except）

**Comment by manas42** [comment]
try：鼓嘟鼓嘟
except：整岔劈了

**Comment by Somiona** [comment]
鼓嘟鼓嘟 [保准 <能成>] 开整：
。。。。。。
[<咋>] 整岔劈了：# except
。。。。。
可算成了：  # final
。。。。。



<能成> -> <Bool> |  <BoolExpr>
<咋> -> <String>
[<X>] -> <X> | ε

**Comment by zhanyong-wan** [comment]
raise MyException()

咋说？

**Comment by Somiona** [comment]
妈耶完犊子了，MyException()?

**Comment by zhanyong-wan** [comment]
'保准'已经上线了。

**Comment by zhanyong-wan** [comment]
‘整劈叉了’也上线了。
