### ISSUE TITLE
为识别带有关键词的标识符，可以尝试按语法分词

### ISSUE THREAD

**Issue by nobodxbodon** [zhanyong-wan/dongbei#112]
看到现在标识符如果包含关键词则需用【】包裹。
最近对rply作了点修改以验证不用额外符号识别带有关键词的标识符，貌似可行，详见 [拙文](https://zhuanlan.zhihu.com/p/411793590)。
这里是对应的 [测试用例](https://github.com/nobodxbodon/rply/blob/a80d61d2c8bfa73b09f1982b267a61dc047918f6/tests/test_%E6%8C%89%E8%AF%AD%E6%B3%95%E5%88%86%E8%AF%8D.py#L122)

**Comment by zhanyong-wan** [comment]
目前这个 issue 的信息不足，如果有具体方案，欢迎重开讨论。谢谢！

**Comment by nobodxbodon** [comment]
作了个 [简单演示](https://github.com/nobodxbodon/rply/blob/09bb8fe20cddc466ec2eec08124930c96459eb74/tests/test_%E6%8C%89%E8%AF%AD%E6%B3%95%E5%88%86%E8%AF%8D%E4%B8%9C%E5%8C%97.py#L83) 实现解析和转换：`装嘀咕装二。嘀咕：装嘀咕。`===> `装嘀咕=2; print(装嘀咕);`

语法规则部分如下：

```python
        @分析器母机.语法规则("代码 : 各句 句号")
        def 各句(片段):
            return 片段[0] + ';'

        @分析器母机.语法规则("各句 : 句")
        @分析器母机.语法规则("各句 : 各句 句号 句")
        def 各句(片段):
            if len(片段) == 1:
                return f"{片段[0]};"
            if len(片段) == 3:
                return f"{片段[0]} {片段[2]}"

        @分析器母机.语法规则("句 : 变量 | 输出")
        def 句(片段):
            return 片段[0]

        @分析器母机.语法规则("变量 : 标识符 装 二")
        def 变量(片段):
            return f"{片段[0].getstr()}=2"

        @分析器母机.语法规则("输出 : 嘀咕 冒号 标识符")
        def 输出(片段):
            return f"print({片段[2].getstr()})"
```
