### ISSUE TITLE
在Windows机器上运行 dongbei脚本发生FileNotFoundError

### ISSUE THREAD

**Issue by TinQlo** [zhanyong-wan/dongbei#114]
操作系统：Windows 10， Windows 11
Python 版本：Python 3.9.7
dongbei 安装方式及版本：pip 为所有用户安装，dongbei-lang 0.0.11

步骤：打开 cmd，输入 “dongbei 磨叽.dongbei”，按回车

报错：FileNotFoundError: [Errno 2] No such file or directory: 'D:\\py397\\Scripts\\dongbei'
![image](https://user-images.githubusercontent.com/30965687/158018844-19d87d06-76c9-4884-aaa0-6e7ebd58c48c.png)

但是去 D:\\py397\\Scripts 下，发现有一个 dongbei.exe 可执行文件
![image](https://user-images.githubusercontent.com/30965687/158018871-5303bf5e-a172-4269-a294-5f428c7ba1e6.png)

**Comment by zhanyong-wan** [comment]
修好啦：https://github.com/zhanyong-wan/dongbei/commit/46436dc0c38c38c9c47d949c8056465da0f29d92

**Comment by TinQlo** [comment]
thanks @zhanyong-wan  成了😸
但是如下结果是直接使用的最新的dongbei.py运行的，pypi的包并没有更新。可以搞一个GitHub actions Publish Python Package，支持配置成如果检测到git推送来的setup.py某字段有更新，就自动打包上传pypi，蛮好玩的。
![image](https://user-images.githubusercontent.com/30965687/166137237-bd8705af-70a4-4069-883a-2e9f7c08ab6e.png)

**Comment by zhanyong-wan** [comment]
发布了 0.0.13 版。
