### ISSUE TITLE
建议增加“你瞅啥”+“瞅你咋地”

### ISSUE THREAD

**Issue by Lakr233** [zhanyong-wan/dongbei#17]
众所周知，瞅你咋地容易干架导致被kill，那不如？

用法：

老王装一       # laowang = 1
你瞅啥老王   # assert(laowang)

老李装假       # laoli = 0
瞅老李咋滴   # assert(!laoli)

**Comment by yuan1238y** [comment]
哈哈哈哈哈哈，这个Feature有意思。

**Comment by orcasdli** [comment]
给老铁整个火箭！

**Comment by zhanyong-wan** [comment]
"你瞅啥“准备用于实现https://github.com/zhanyong-wan/dongbei/issues/82
