### ISSUE TITLE
我是天津码农，遵循开源协议的情况下，能fork一个天津话版本的项目吗

### ISSUE THREAD

**Issue by eggfly** [zhanyong-wan/dongbei#18]
【阶乘】（几）介恁么算：# 函数定义，函数名是【阶乘】有一个参数，几
    几比一小，介对嘛？ # if 语句
    倍儿对，尼了白白吧 一。 # return 1
    瞎鬼，尼了白白吧 您受累吧【阶乘】（几减一）。# 您受累吧 是函数调用， return 阶乘(n-1)
齐活。

**Comment by blaisewang** [comment]
虽然我不是作者，但遵循MIT协议的情况下完全没问题

**Comment by zhanyong-wan** [comment]
嘛毛病没有！您请吧。
