### ISSUE TITLE
建议“退退”改为“稍稍”

### ISSUE THREAD

**Issue by dragonwong** [zhanyong-wan/dongbei#19]
该提案来自东百著名快手程序员：阿giao

**Comment by zhanyong-wan** [comment]
东北银解释一下：稍稍啥意思啊？

**Comment by dragonwong** [comment]
`稍稍` 一般意义同 `退退`，也暗合计算机语音中的 `--`，表示数值的减少。

`稍稍` 这个词具有十分浓厚的地方风味，尤其在东北大老哥向社会小老弟传授人生的经验时，出现得尤为频繁，体现了东北人民的儒雅随和，平易近人。近年来随着各种视频、社交平台的发展，这个东北词汇也受到了来自社会各界人士的喜爱。

![image](https://imgsa.baidu.com/forum/w%3D580/sign=9fceb0b88f26cffc692abfba89004a7d/c3e3a41fbe096b63deaf987101338744eaf8ac87.jpg)

![image](http://img.itlun.cn/uploads/allimg/171204/1-1G204212H1.jpg)

**Comment by zhanyong-wan** [comment]
唉呀大哥你这解释还真是鞭辟入了里咧。那“退两步”该咋讲呢？能说“稍两步”吗？

**Comment by dragonwong** [comment]
@zhanyong-wan 当然可以。如果我们在写 `稍` 时口中默念它的独特东北发音：`shào`，那么我们的代码将会更加地道，更有内味了。

**Comment by zhanyong-wan** [comment]
老铁，[整好咧](https://github.com/zhanyong-wan/dongbei/commit/fdb12dd17e96510d68bb84f544842b9b34a0522f)。

**Comment by dragonwong** [comment]
老铁，666
