### ISSUE TITLE
请问如何导入 python 模块？

### ISSUE THREAD

**Issue by nobodxbodon** [zhanyong-wan/dongbei#20]
好像说明没有提及？

**Comment by zhanyong-wan** [comment]
这会儿还整不了。我寻思可以

```
翠花，上sys。
```

**Comment by SaltNego** [comment]
来，把requests伶出来；

**Comment by zhanyong-wan** [comment]
成了：

https://github.com/zhanyong-wan/dongbei/commit/f4012c4caa466785310b6ad81820901ced31286b
