### ISSUE TITLE
建议添加0xcc为”太ye了“的彩蛋

### ISSUE THREAD

**Issue by HaoYejia** [zhanyong-wan/dongbei#26]
众所周知，0xcc转换为字符串即为”烫“（如C语言中的经典报错”烫烫烫“），为符合东北人（尤其是气质，可添加0xcc为”太ye了“的彩蛋

**Comment by duhaoze11** [comment]
0xcd“屯”倒简单一点，就“屯儿”就行了23333333
复杂的是utf-8: \xef\xbf \xbd\xef \xbf\xbd“锟斤拷”怎么处理233333333

**Comment by xiangzhai** [comment]
> 众所周知，0xcc转换为字符串即为”烫“（如C语言中的经典报错”烫烫烫“），为符合东北人（尤其是气质，可添加0xcc为”太ye了“的彩蛋

YEYEYE+1

**Comment by zhanyong-wan** [comment]
很多更重要的功能要加，这个优先级低。
