### ISSUE TITLE
整了个斐波那契的套路，这代码风格笑死我了。期待多整个数组相关功能。

### ISSUE THREAD

**Issue by CSY-tvgo** [zhanyong-wan/dongbei#29]
![image](https://user-images.githubusercontent.com/22344414/73953819-ea3d3780-493b-11ea-9857-86ef2221c2da.png)

例如：
老万是活雷锋。
老万装“这个好！”。
唠唠：老万的第二个嘎达。  # 打印“个”

**Comment by CSY-tvgo** [comment]
哦对了，还发现个bug，给套路传入类似“-1”的负数时无法正常运行。

**Comment by zhanyong-wan** [comment]
看把你能的。牛叉大了啊！

暂时还不能处理负的常数。

**Comment by zhanyong-wan** [comment]
把你这套路送个PR吧，加个新的demo。

**Comment by CSY-tvgo** [comment]
@zhanyong-wan 已PR，还加了个北京儿话儿转换儿器儿
