### ISSUE TITLE
咋定义数组啊

### ISSUE THREAD

**Issue by Dusk-Till-Dawn** [zhanyong-wan/dongbei#3]
如题 咋定义数组

**Comment by zhanyong-wan** [comment]
目前还整不了。以后考虑用这个语法：

老张家是活雷锋。  # laozhang 是个数组
老张家老大装5。  # laozhang[0] = 5
老张家老7装9。 # laozhang[6] = 9

**Comment by Dusk-Till-Dawn** [comment]
可不可以考虑用这个语法：
老张和他的101个兄弟都是活雷锋 //不太会Python 此处用c++语法：int laozhang[101];

**Comment by Lighitng** [comment]
再整个：
老张家有几口人（数组长度）
老张家有套家规（定义class，对内private对外public，protect没想好。）
老张家有个人叫XX（定义类的实例）
老张家有个儿子叫小明（继承）
老张家儿子小明有个大姨叫老李（多继承）

**Comment by ouuan** [comment]
> 可不可以考虑用这个语法：
> 老张和他的101个兄弟都是活雷锋 //不太会Python 此处用c++语法：int laozhang[101];

这不整一起有 102 个人吗。

**Comment by ouuan** [comment]
这样整咋样：

```python
【张家村】是个村 #张家村 = []
【张家村】是个人们装3装4的村 #张家村 = [3, 4]
【张家村】里第2个人装7 #张家村[1] = 7, 这里下标从 1 开始
【张家村】来了个装2的人 #张家村.append(2)
老王和【张家村】里每个人依次磨叽 # for 老王 in 张家村
```

“家”可以用来整 class。

**Comment by zhanyong-wan** [comment]
哎呀妈呀，这张家村老有才了！

**Comment by MinuteSphinx** [comment]
我觉得遍历可以这么简化
老王来查张家村

**Comment by jcq15** [comment]
> 我觉得遍历可以这么简化
> 老王来查张家村

我觉得“查”可以改成“瞅”
老王来瞅张家村

**Comment by zhanyong-wan** [comment]
基本的数组（群众）操作弄好了：

单只单只的活雷锋有的时候略显捉襟见肘。dongbei 支持“群众”的概念。就是一个变量里放一群活雷锋。有学习好的同学可能发觉了：这不就是**数组**吗！

比如：
```
张家庄都是活雷锋。  # 张家庄是个群众变量。初始值是[]。
```

完了吧就可以往里边儿加人了：
```
张家庄来了一个二加三。  # 张家庄现在 = [5]。
张家庄来了一个“大”。   # 张家庄现在 = [5, '大']
张家庄来了一个四减一。  # 张家庄现在 = [5, '大', 3]
张家庄来了一个“粗”。   # 张家庄现在 = [5, '大', 3, '粗']
```

加完人就可以点名了：
```
唠唠：张家庄的老大。  # 第一个人（5）。
唠唠：张家庄的老二。  # 第二个人（'大'）。
唠唠：张家庄的老（四减一）。  # 第三个人（3）。
唠唠：张家庄的老四。  # 第四个人（'粗')。
唠唠：张家庄的老一。  # 跟老大一回事。
唠唠：张家庄的老幺。  # 最后一个人（'粗')。
```

既然数组里头可以套数组，那么群众当中也可以套群众：
```
李家村都是活雷锋。  # 李家村也是个群众变量。初始值是[]。
李家村来了一个三。  # 李家村现在 = [3]。
李家村来了一个张家庄。  # 李家村现在 = [3, [5, '大', 3, '粗']]。
唠唠：李家村的老幺的老大。  # 5。
```

要想团灭群众，只需要削他：
```
削张家庄。  # 张家庄现在啥也不是。
```
