### ISSUE TITLE
建议增加输入

### ISSUE THREAD

**Issue by Dusk-Till-Dawn** [zhanyong-wan/dongbei#33]
一门语言没有输入问题很大啊
建议以跟xx唠唠作为输入
如：跟老王唠唠 #向老王里输入数值

**Comment by zhanyong-wan** [comment]
输入本身可以是表达式的一部分，不一定要跟一个变量绑在一起。

有人建议用“别人唠的”，可以避免这个问题。比如：

```
唠唠：“你说：”、别人唠的。
```

**Comment by zhanyong-wan** [comment]
跟 https://github.com/zhanyong-wan/dongbei/issues/42 重了。
