### ISSUE TITLE
建议修改墨迹语法为：老王从X磨叽到Y

### ISSUE THREAD

**Issue by vkensou** [zhanyong-wan/dongbei#36]
这样语法更通顺
```
老王从1磨叽到9：
    ....
磨叽完了。
```

**Comment by zhanyong-wan** [comment]
数组，咳咳，群众的磨叽语法是：

老王在王家庄磨叽：
  ...

为了一致，还是把磨叽放在最后吧。

**Comment by vkensou** [comment]
> 数组，咳咳，群众的磨叽语法是：
> 
> 老王在王家庄磨叽：
> ...
> 
> 为了一致，还是把磨叽放在最后吧。

既然是东北话，就按东北话的规矩来啊，这才叫【一致】啊

**Comment by zhaozheid** [comment]
还好看了下 Issue 关了，差点就准备干PR了。。
