### ISSUE TITLE
建议增加“你跟谁俩呢？”

### ISSUE THREAD

**Issue by Rossitte** [zhanyong-wan/dongbei#38]

**Comment by zhanyong-wan** [comment]
啥意思？

**Comment by manmanhensha** [comment]
哈哈，附议

**Comment by jcq15** [comment]
布尔值？
true：老铁没毛病！
false：跟谁俩呢？

**Comment by Rossitte** [comment]
> 布尔值？
> true：老铁没毛病！
> false：跟谁俩呢？

我本来就随便说说...但是你这么一说我怎么觉得你说的好有道理

**Comment by zombie110year** [comment]
建议缩减一下：
`true`: 没毛病；`false`：谁俩呢。
这样比较容易和语句结合

**Comment by zhanyong-wan** [comment]
`谁俩呢`在上下文当中念着不太顺，把对错改成 没毛病/有毛病 了。

https://github.com/zhanyong-wan/dongbei/commit/42265a40175aeefc6c426ce945177389e822a037
https://github.com/zhanyong-wan/dongbei/commit/c2bbb5beeb602c506e2746c4bcf286ef70b40986
