### ISSUE TITLE
我 jio 得吧 该启用“那啥”了

### ISSUE THREAD

**Issue by IoriOikawa** [zhanyong-wan/dongbei#4]
瞅完了文档 俺跟俺老婆勒勒了一下
俺们都觉得 那个“几”吧 有点儿问题
既然咱说了 dongbei 是个不需要 specifier 的玩意儿
那说“几”这个词就有点儿小了对吧 你看这样好不好使哈——
```
【阶乘】咋整：  # 定义套路 阶乘，有一个参数 那啥
  老王是活雷锋。
  老王装一。
  老李从一到那啥磨叽：
    老王装老王乘老李。
  磨叽完了。
  滚犊子吧老王！  # 返回值。
整完了。  # 定义结束。
```

然后吧 你说你想搞多点儿仁儿进去
那就 那啥那啥 就行了呗
```
foo咋整：
    bar咋整：
        滚犊子吧那啥那啥加那啥
    整完了。
    滚犊子吧 bar
整完了。
```
就 酱婶儿的——
```javascript
function foo(a) {
  function bar(b) {
    return a + b;
  }
  return bar;
}
```

**Comment by zhanyong-wan** [comment]
主意不错啊！可那啥参数要有十个八个的咋整啊？

**Comment by xycforgithub** [comment]
那啥，那啥啥，那啥啥啥

**Comment by Co2333** [comment]
那啥啥啥啥啥啥啥啥啥啥啥啥啥啥啥啥啥啥

**Comment by t532** [comment]
是不是学的 [Finally Tagless Interpreter](https://www.codewars.com/kata/5424e3bc430ca2e577000048/)（

**Comment by zhanyong-wan** [comment]
好吧，把所有例子里的‘几’都改‘那啥’了。

不过参数名还是不要强制为‘那啥’，‘那啥啥’吧，头会炸的。

**Comment by IoriOikawa** [comment]
> 主意不错啊！可那啥参数要有十个八个的咋整啊？

咱东北人说话都直，一个事儿就是一个事儿，一码是一码；
整个事儿做，结果一堆那啥，其他人听都听不懂看着眼晕，膈不膈应人啊。

俺明白不少大小伙子老少爷们姑娘媳妇儿在把一堆算法捏咕成一个的时候总是搞哪那么一大长串砸，
或者处对象儿的时候总是想把对象鼓逑小点儿，结果搞一堆参数看着脑壳火辣辣的疼；
要是哥几个不介意 我就革这儿瞎掰了—— 真地啊 都长点儿心吧：

你要是把自己撂一堆散沙里想捏咕出办法， 你啊寻思一下，先瞅瞅你那堆参数——
其一 你那堆参数如果是搁别的对象儿里捣鼓出来的，你就把“那啥”换成对象儿的方法咋样？
其二 你要是发现你那对象儿能给你搞一堆参数，那你干脆把对象儿请你家里整呗？
其三 你要是感脚你那堆参数之间没啥关系，那你干脆把那团散沙包起来搞个对象儿成不成？

那帮文明人儿把这三种办法叫做
Replace Parameter with Method Call
Preserve Whole Object
Introduce Parameter Object

咱哪儿说哪儿了哈，处不处对象儿这事儿咱先不说，人生大事儿嘛。
可但四！俺就是想坚决刹住某些人那股子“一股脑儿倒参数”的歪风～
害有，别想着为了啥都能干就忘了本儿，咱这是东北话，你要是把东北话的好处也给介绍进来，
那你整挺好，可谓就相当牛逼了，为了把这玩意儿搞出个啥名堂，好说好使，以求达到那个机器开心人也开心的境界，咱都得加个油啊！
