### ISSUE TITLE
基于范围的磨叽部分的语法好像有点问题，例如这段代码不能正常运行

### ISSUE THREAD

**Issue by PairZhu** [zhanyong-wan/dongbei#41]
张家庄都是活雷锋。
张家庄来了一个五。
张家庄来了一个俩。
张家庄来了一个零。
【老张】在【张家庄】磨叽：
  唠唠：老张。
磨叽完了。

**Comment by zhanyong-wan** [comment]
具体啥错误啊？

**Comment by zhanyong-wan** [comment]
你这语法过时了。看最新文档，说“来了个”，憋说“来了一个”。
