### ISSUE TITLE
建议添加「村」or「屯」（class）

### ISSUE THREAD

**Issue by f612** [zhanyong-wan/dongbei#48]
虽然不是东北人
但是离了Class的Python真的没有什么意思（。）

**Comment by ouuan** [comment]
Reference: https://github.com/zhanyong-wan/dongbei/issues/3#issuecomment-581733580

**Comment by zhanyong-wan** [comment]
‘村’ 已经用作群众变量的命名惯例了。得换个词儿。

**Comment by f612** [comment]
我想不到了
我能想到的只有啥“家”、“班子”、“社”、“团”

**Comment by Vampriest** [comment]
可以用“大队”。

**Comment by Xiao8Yang** [comment]
窝棚

**Comment by zombie110year** [comment]
噶嗒？

**Comment by xinxiao** [comment]
推荐 `帅小伙` 

因为  `帅小伙` 长得规范

**Comment by zhanyong-wan** [comment]
class 的标准翻译 “阶级” 揍挺好！

```
无产阶级的接班人 XX 阶级咋整：  # 定义 XX class, 没有 parent class。
  新对象（YY）咋整：  # def __init__(self, YY):
    俺的YY 装 YY。  #  self.YY = YY
  整完了
整完了。

【小李】装XX阶级的新对象（二）。  # 小李 = XX(2)
唠唠：【小李】的YY。  # print(小李.YY）

XX 阶级的接班人 ZZ 阶级咋整：  # 定义 ZZ class, parent class 是 XX。
  ...
整完了。
```

**Comment by zhanyong-wan** [comment]
第一步: https://github.com/zhanyong-wan/dongbei/commit/30277ee621c0ac217b589abccba2367cc634edc3

**Comment by zhanyong-wan** [comment]
整好了： https://github.com/zhanyong-wan/dongbei#%E9%98%B6%E7%BA%A7

**Comment by suxpert** [comment]
“新对象”不如复用“活雷锋”得劲儿：
```
无产阶级接班银 工人阶级 咋整：
    活雷锋（YY）咋整：
        自个儿的 YY 装 YY。
    整完了。
整完了。

# 复用“老李是活雷锋”句法，毕竟都是初始化
老李 是 工人阶级活雷锋（鸭蛋）。
```

**Comment by zhanyong-wan** [comment]
`XX 是活雷锋` 整出一个空对象。
`XXX 都是活雷锋` 整出一个空列表。

`XX 是工人阶级活雷锋` 整出一个新对象（不是空的），有点不一致。
而且 `XXX 都是工人阶级活雷锋` 又咋整呢？目前不打算引入 static typing。
