### ISSUE TITLE
为啥整不了阿

### ISSUE THREAD

**Issue by mfp0610** [zhanyong-wan/dongbei#5]
`bash: src/dongbei.py: /usr/local/bin/python3: 解释器错误: 没有那个文件或目录`

**Comment by zhanyong-wan** [comment]
你把python3装哪嘎哒了？

**Comment by mfp0610** [comment]
home/user/local/lib/python3.6 装zei坎儿了

**Comment by HarukaFuture** [comment]
用您的包管理器整一个蟒蛇3似乎就好

**Comment by zhanyong-wan** [comment]
HarukaFuture 帮整好了！
