### ISSUE TITLE
加如flag来控制编译器的附属功能，比如现在每次都在打印AST。

### ISSUE THREAD

**Issue by xinxiao** [zhanyong-wan/dongbei#54]
现在每次运行`dongbei`解释器都会自动打印`dongbei-lang`的ast，debug时容易让人感觉啰嗦，令人急躁，使人吵吵巴火。

建议加如flag来控制编译器的附属功能。

**Comment by zhanyong-wan** [comment]
瞅瞅 https://github.com/zhanyong-wan/dongbei/commit/3138e42272bfcde925583b46784edafb556d919e

**Comment by xinxiao** [comment]
O了

**Comment by zhanyong-wan** [comment]
我寻思吧，verbose 不够接地气，改 jiwai （叽歪）了。

**Comment by xinxiao** [comment]
叽歪感觉差点儿意思，xyudao（絮叨）咋样？

**Comment by zhanyong-wan** [comment]
絮叨好

**Comment by zhanyong-wan** [comment]
https://github.com/zhanyong-wan/dongbei/commit/bcf67a4336190e30aea809ef8280cb0b2604fe47
