### ISSUE TITLE
再怎么也不能忘本啊,要支持传统文化python2

### ISSUE THREAD

**Issue by Songyu-Wang** [zhanyong-wan/dongbei#6]

**Comment by zhanyong-wan** [comment]
不是我埋汰他啊，这蛇老二吧太爱死磕（ASCII），对有礼口德（Unicode）的支持度实在太寒碜了！伤不起啊伤不起。。。 还是蛇老三 OK !

**Comment by Songyu-Wang** [comment]
haha, jkjk
Closing this issue since its just for a joke
