### ISSUE TITLE
建议增加 list 字面赋值

### ISSUE THREAD

**Issue by suxpert** [zhanyong-wan/dongbei#70]
目前的 dongbei 里面，创建群众的语法有点繁琐：
```
王家庄都是活雷锋。
王家庄来了个一。
王家庄来了个二。
王家庄来了个三。
```

但是王家庄也可以本来就有居民哇。建议增加支持，例如：
```
# w = [a,b,c,0]
王家庄这嘎瘩吧 老王头，老李头，老孙头，鸭蛋 包圆儿
```

**Comment by mike-unk** [comment]
帮你@zhanyong-wan，这样写qsort就简单一点了

**Comment by zhanyong-wan** [comment]
https://github.com/zhanyong-wan/dongbei/commit/3dd7dc4d421afb57734ae3ca3ad47cdbb7ae7698

**Comment by suxpert** [comment]
哥，我有个小小的建议。咱不能光为了添加功能就把东北话的精髓给丢了呀……竖引号是好使，但竖引号妹有音效啊！

**Comment by zhanyong-wan** [comment]
dongbei 语言设计遵循迭代大法，程序多了加音效，音效多了加程序。哪样太多都不成。

这样吧，再加个带音效的版本，大伙自己爱用哪个用哪个。

**Comment by zhanyong-wan** [comment]
https://github.com/zhanyong-wan/dongbei/commit/08bc352b0b858ef029d69f8aa47ebc88b864db1c
