### ISSUE TITLE
建议负号用“拉饥荒”

### ISSUE THREAD

**Issue by suxpert** [zhanyong-wan/dongbei#71]
```
老王 装 拉饥荒 三百
```

要是后面这个三百真能支持也挺好。浮点数还可以是
```
老李 装 拉饥荒 一百三十二块五毛八
```

**Comment by zhanyong-wan** [comment]
拉饥荒不错

**Comment by zhanyong-wan** [comment]
好咧：https://github.com/zhanyong-wan/dongbei/commit/80fc795c0d706e1b763f2b414230624a34609eee
