### ISSUE TITLE
yield 东北话咋说

### ISSUE THREAD

**Issue by zhanyong-wan** [zhanyong-wan/dongbei#95]
想支持 yield ，就是没想好东北话该咋说。大伙儿支个招？

**Comment by suxpert** [comment]
我寻思了半天，“出溜”应该还成吧。

“拉倒”感觉回不来了；
“滚蛋”太不和谐容易干仗；
要是不怕谐音梗扣钱，也可以直接念成“丫蛋儿”，但是“鸭蛋”又表示不乐意。

**Comment by weijiang1994** [comment]
街溜子吧 挺符合的 溜一圈又回来了

**Comment by zhanyong-wan** [comment]
出溜弄好了：https://github.com/zhanyong-wan/dongbei/commit/374ed72c883c13a41a1359a559fe0f86ffa670c0
