### ISSUE TITLE
建议这玩意儿可以包装下，学学“中科院木兰事件”，号称100%国产自主研发，技术可控，去骗个几亿经费

### ISSUE THREAD

**Issue by shmchen** [zhanyong-wan/dongbei#99]

**Comment by nobodxbodon** [comment]
木兰重现项目已开源[在码云](https://gitee.com/MulanRevive/mulan-rework)。
最新进展在「木兰编程语言」[知乎专栏](https://zhuanlan.zhihu.com/ulang)。
走着。
